name: 'Build and Push Docker Image'
description: 'Builds and pushes a Docker image to a container registry'
inputs:
  application-name:
    description: 'Application name for image tagging'
    required: true
  registry:
    description: 'Container registry (e.g., ghcr.io, docker.io)'
    required: false
    default: 'ghcr.io'
  registry-username:
    description: 'Container registry username'
    required: false
  registry-token:
    description: 'Container registry token/password'
    required: true
  context:
    description: 'Docker build context directory'
    required: false
    default: '.'
  dockerfile:
    description: 'Path to Dockerfile'
    required: false
    default: 'Dockerfile'
  image-tag:
    description: 'Custom image tag'
    required: false
    default: ''
  environment:
    description: 'Environment name (dev, test, prod)'
    required: false
    default: 'dev'
  push:
    description: 'Whether to push the image'
    required: false
    default: 'true'
  build-args:
    description: 'Build arguments (one per line)'
    required: false
    default: ''

outputs:
  image-name:
    description: 'Full image name with tag'
    value: ${{ steps.meta.outputs.tags }}
  image-digest:
    description: 'Image digest'
    value: ${{ steps.build-push.outputs.digest }}
  image-tag:
    description: 'Image tag used'
    value: ${{ steps.generate-tag.outputs.tag }}

runs:
  using: 'composite'
  steps:
    - name: Generate Image Tag
      id: generate-tag
      shell: bash
      run: |
        if [ -n "${{ inputs.image-tag }}" ]; then
          echo "tag=${{ inputs.image-tag }}" >> $GITHUB_OUTPUT
        else
          echo "tag=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
        fi

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      if: ${{ inputs.push == 'true' }}
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.registry-username }}
        password: ${{ inputs.registry-token }}

    - name: Extract Repository Name
      id: repo-name
      shell: bash
      run: |
        REPO_NAME=$(echo "${GITHUB_REPOSITORY}" | tr '[:upper:]' '[:lower:]')
        echo "repo_name=$REPO_NAME" >> $GITHUB_OUTPUT

    - name: Extract Metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.registry }}/${{ steps.repo-name.outputs.repo_name }}/${{ inputs.application-name }}
        tags: |
          type=raw,value=${{ steps.generate-tag.outputs.tag }}
          type=raw,value=${{ inputs.environment }}
          type=raw,value=latest,enable=${{ inputs.environment == 'prod' }}

    - name: Build and Push
      id: build-push
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        push: ${{ inputs.push }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: ${{ inputs.build-args }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        provenance: false
